ROOT: "./datasets"
ANNO_FILE: "./datasets/anno.json"
INPUT:
  HEIGHT: 512
  WIDTH: 512
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
MODEL:
  MOTIONVAE:
    IN_CHANNELS: 3
    LATENTDIM: 128
    KLD_WEIGHT: 0.0005


SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 128

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "./output/"
